export const CHAMPION_PETS: Record<string, string[]> = {
  Anivia: ['aniviaegg', 'aniviaiceblock'],
  Annie: ['annietibbers'],
  Aphelios: ['apheliosturret'],
  Aurora: ['auroraspirits'],
  Azir: ['azirsoldier', 'azirsundisc', 'azirtowerclicker', 'azirultsoldier'],
  Bard: ['bardfollower'],
  Belveth: ['belvethspore', 'belvethvoidling'],
  Caitlyn: ['caitlyntrap'],
  Elise: ['elisespider', 'elisespiderling'],
  Fizz: ['fizzbait', 'fizzshark'],
  Gangplank: ['gangplankbarrel'],
  Gnar: ['gnarbig'],
  Heimerdinger: ['heimertblue', 'heimertyellow'],
  Illaoi: ['illaoiminion'],
  Irelia: ['ireliablades'],
  Ivern: ['ivernminion', 'iverntotem'],
  JarvanIV: ['jarvanivstandard', 'jarvanivwall'],
  Jhin: ['jhintrap'],
  Jinx: ['jinxmine'],
  Kalista: ['kalistaaltar', 'kalistaspawn'],
  Kindred: ['kindredwolf'],
  Kled: ['kledmount', 'kledrider'],
  KogMaw: ['kogmawdead'],
  Lulu: ['luludragon', 'lulufaerie', 'lulujellyfish', 'lulupolymorphcritter'],
  Malzahar: ['malzaharvoidling'],
  Maokai: ['maokaisproutling'],
  Milio: ['miliominion'],
  MonkeyKing: ['monkeykingclone', 'monkeykingflying'],
  Naafiri: ['naafiripackmate'],
  Nasus: ['nasusult'],
  Nidalee: ['nidaleecougar', 'nidaleespear'],
  Nunu: ['nunusnowball'],
  Olaf: ['olafaxe'],
  Orianna: ['oriannaball', 'oriannanoball'],
  Quinn: ['quinnvalor'],
  Rammus: ['rammusdbc', 'rammuspb'],
  RekSai: ['reksaitunnel'],
  Senna: ['sennasoul'],
  Shaco: ['shacobox'],
  Shyvana: ['shyvanadragon'],
  Swain: ['swaindemonform'],
  Syndra: ['syndraorbs', 'syndrasphere'],
  Taliyah: ['taliyahwallchunk'],
  Teemo: ['teemomushroom'],
  Thresh: ['threshlantern'],
  Udyr: [
    'udyrphoenix',
    'udyrphoenixult',
    'udyrtiger',
    'udyrtigerult',
    'udyrturtle',
    'udyrturtleult',
    'udyrult'
  ],
  Yorick: ['yorickbigghoul', 'yorickghoulmelee', 'yorickwghoul'],
  Zac: ['zacrebirthbloblet'],
  Zed: ['zedshadow'],
  Zoe: ['zoeorbs'],
  Zyra: ['zyragraspingplant', 'zyrapassive', 'zyraseed', 'zyrathornplant']
}

export function getPetNamesForChampion(championKey: string): string[] {
  return CHAMPION_PETS[championKey] ?? []
}
